export const BASE_URL = 'Telegram-Animated-Emojis';

// Helper to strip variation selectors (VS16 - \uFE0F) for consistent matching
const normalize = (str) => {
    if (!str) return '';
    // Strip VS15/VS16 (\uFE0E, \uFE0F), skin tones (\u{1F3FB}-\u{1F3FF}), and ZWJ (\u200D)
    return str.replace(/[\uFE0E\uFE0F\u200D\u{1F3FB}-\u{1F3FF}]/gu, ''); 
};

// Map keys should be normalized (no VS16)
export const ANIMATED_EMOJIS = {
    // Smileys
    [normalize("😁")]: `${BASE_URL}/Smileys/Beaming%20Face%20With%20Smiling%20Eyes.webp`,
    [normalize("😂")]: `${BASE_URL}/Smileys/Face%20With%20Tears%20Of%20Joy.webp`,
    [normalize("😃")]: `${BASE_URL}/Smileys/Grinning%20Face%20With%20Big%20Eyes.webp`,
    [normalize("😄")]: `${BASE_URL}/Smileys/Grinning%20Face%20With%20Smiling%20Eyes.webp`,
    [normalize("😅")]: `${BASE_URL}/Smileys/Grinning%20Face%20With%20Sweat.webp`,
    [normalize("😆")]: `${BASE_URL}/Smileys/Grinning%20Squinting%20Face.webp`,
    [normalize("😉")]: `${BASE_URL}/Smileys/Winking%20Face.webp`,
    [normalize("😊")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Smiling%20Eyes.webp`,
    [normalize("😋")]: `${BASE_URL}/Smileys/Face%20Savoring%20Food.webp`,
    [normalize("😎")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Sunglasses.webp`,
    [normalize("😍")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Heart-Eyes.webp`,
    [normalize("😘")]: `${BASE_URL}/Smileys/Face%20Blowing%20A%20Kiss.webp`,
    [normalize("🥰")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Hearts.webp`,
    [normalize("😗")]: `${BASE_URL}/Smileys/Kissing%20Face.webp`,
    [normalize("😙")]: `${BASE_URL}/Smileys/Kissing%20Face%20With%20Smiling%20Eyes.webp`,
    [normalize("😚")]: `${BASE_URL}/Smileys/Kissing%20Face%20With%20Closed%20Eyes.webp`,
    [normalize("🙂")]: `${BASE_URL}/Smileys/Slightly%20Smiling%20Face.webp`,
    [normalize("🤗")]: `${BASE_URL}/Smileys/Hugging%20Face.webp`,
    [normalize("🤩")]: `${BASE_URL}/Smileys/Star-Struck.webp`,
    [normalize("🤔")]: `${BASE_URL}/Smileys/Thinking%20Face.webp`,
    [normalize("🤨")]: `${BASE_URL}/Smileys/Face%20With%20Raised%20Eyebrow.webp`,
    [normalize("😐")]: `${BASE_URL}/Smileys/Neutral%20Face.webp`,
    [normalize("😑")]: `${BASE_URL}/Smileys/Expressionless%20Face.webp`,
    [normalize("😶")]: `${BASE_URL}/Smileys/Face%20Without%20Mouth.webp`,
    [normalize("🙄")]: `${BASE_URL}/Smileys/Face%20With%20Rolling%20Eyes.webp`,
    [normalize("😏")]: `${BASE_URL}/Smileys/Smirking%20Face.webp`,
    [normalize("😣")]: `${BASE_URL}/Smileys/Persevering%20Face.webp`,
    [normalize("😥")]: `${BASE_URL}/Smileys/Sad%20But%20Relieved%20Face.webp`,
    [normalize("😮")]: `${BASE_URL}/Smileys/Face%20With%20Open%20Mouth.webp`,
    [normalize("🤐")]: `${BASE_URL}/Smileys/Zipper-Mouth%20Face.webp`,
    [normalize("😯")]: `${BASE_URL}/Smileys/Hushed%20Face.webp`,
    [normalize("😪")]: `${BASE_URL}/Smileys/Sleepy%20Face.webp`,
    [normalize("😫")]: `${BASE_URL}/Smileys/Tired%20Face.webp`,
    [normalize("😴")]: `${BASE_URL}/Smileys/Sleeping%20Face.webp`,
    [normalize("😌")]: `${BASE_URL}/Smileys/Relieved%20Face.webp`,
    [normalize("😛")]: `${BASE_URL}/Smileys/Face%20With%20Tongue.webp`,
    [normalize("😜")]: `${BASE_URL}/Smileys/Winking%20Face%20With%20Tongue.webp`,
    [normalize("😝")]: `${BASE_URL}/Smileys/Squinting%20Face%20With%20Tongue.webp`,
    [normalize("🤤")]: `${BASE_URL}/Smileys/Drooling%20Face.webp`,
    [normalize("😒")]: `${BASE_URL}/Smileys/Unamused%20Face.webp`,
    [normalize("😓")]: `${BASE_URL}/Smileys/Downcast%20Face%20With%20Sweat.webp`,
    [normalize("😔")]: `${BASE_URL}/Smileys/Pensive%20Face.webp`,
    [normalize("😕")]: `${BASE_URL}/Smileys/Confused%20Face.webp`,
    [normalize("🙃")]: `${BASE_URL}/Smileys/Upside-Down%20Face.webp`,
    [normalize("🤑")]: `${BASE_URL}/Smileys/Money-Mouth%20Face.webp`,
    [normalize("😲")]: `${BASE_URL}/Smileys/Astonished%20Face.webp`,
    [normalize("☹️")]: `${BASE_URL}/Smileys/Frowning%20Face.webp`,
    [normalize("🙁")]: `${BASE_URL}/Smileys/Slightly%20Frowning%20Face.webp`,
    [normalize("😖")]: `${BASE_URL}/Smileys/Confounded%20Face.webp`,
    [normalize("disappointed")]: `${BASE_URL}/Smileys/Disappointed%20Face.webp`,
    [normalize("worried")]: `${BASE_URL}/Smileys/Worried%20Face.webp`,
    [normalize("😤")]: `${BASE_URL}/Smileys/Face%20With%20Steam%20From%20Nose.webp`,
    [normalize("😢")]: `${BASE_URL}/Smileys/Crying%20Face.webp`,
    [normalize("😭")]: `${BASE_URL}/Smileys/Loudly%20Crying%20Face.webp`,
    [normalize("frowning")]: `${BASE_URL}/Smileys/Frowning%20Face%20With%20Open%20Mouth.webp`,
    [normalize("anguished")]: `${BASE_URL}/Smileys/Anguished%20Face.webp`,
    [normalize("fearful")]: `${BASE_URL}/Smileys/Fearful%20Face.webp`,
    [normalize("weary")]: `${BASE_URL}/Smileys/Weary%20Face.webp`,
    [normalize("grimacing")]: `${BASE_URL}/Smileys/Grimacing%20Face.webp`,
    [normalize("😰")]: `${BASE_URL}/Smileys/Anxious%20Face%20With%20Sweat.webp`,
    [normalize("😱")]: `${BASE_URL}/Smileys/Face%20Screaming%20In%20Fear.webp`,
    [normalize("flushed")]: `${BASE_URL}/Smileys/Flushed%20Face.webp`,
    [normalize("dizzy")]: `${BASE_URL}/Smileys/Dizzy%20Face.webp`,
    [normalize("😡")]: `${BASE_URL}/Smileys/Pouting%20Face.webp`,
    [normalize("😠")]: `${BASE_URL}/Smileys/Angry%20Face.webp`,
    [normalize("😷")]: `${BASE_URL}/Smileys/Face%20With%20Medical%20Mask.webp`,
    [normalize("🤒")]: `${BASE_URL}/Smileys/Face%20With%20Thermometer.webp`,
    [normalize("🤕")]: `${BASE_URL}/Smileys/Face%20With%20Head-Bandage.webp`,
    [normalize("🤢")]: `${BASE_URL}/Smileys/Nauseated%20Face.webp`,
    [normalize("🤮")]: `${BASE_URL}/Smileys/Face%20Vomiting.webp`,
    [normalize("🤧")]: `${BASE_URL}/Smileys/Sneezing%20Face.webp`,
    [normalize("🥵")]: `${BASE_URL}/Smileys/Hot%20Face.webp`,
    [normalize("🥶")]: `${BASE_URL}/Smileys/Cold%20Face.webp`,
    [normalize("🥴")]: `${BASE_URL}/Smileys/Woozy%20Face.webp`,
    [normalize("😵")]: `${BASE_URL}/Smileys/Dizzy%20Face.webp`,
    [normalize("🤯")]: `${BASE_URL}/Smileys/Exploding%20Head.webp`,
    [normalize("🤠")]: `${BASE_URL}/Smileys/Cowboy%20Hat%20Face.webp`,
    [normalize("🥳")]: `${BASE_URL}/Smileys/Partying%20Face.webp`,
    [normalize("🥸")]: `${BASE_URL}/Smileys/Disguised%20Face.webp`,
    [normalize("😈")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Horns.webp`,
    [normalize("👿")]: `${BASE_URL}/Smileys/Angry%20Face%20With%20Horns.webp`,
    [normalize("🤥")]: `${BASE_URL}/Smileys/Lying%20Face.webp`,
    [normalize("🤫")]: `${BASE_URL}/Smileys/Shushing%20Face.webp`,
    [normalize("🤭")]: `${BASE_URL}/Smileys/Face%20With%20Hand%20Over%20Mouth.webp`,
    [normalize("🧐")]: `${BASE_URL}/Smileys/Face%20With%20Monocle.webp`,
    [normalize("🤓")]: `${BASE_URL}/Smileys/Nerd%20Face.webp`,
    [normalize("😀")]: `${BASE_URL}/Smileys/Grinning%20Face.webp`,
    [normalize("😬")]: `${BASE_URL}/Smileys/Grimacing%20Face.webp`,
    [normalize("🥺")]: `${BASE_URL}/Smileys/Pleading%20Face.webp`,
    [normalize("😣")]: `${BASE_URL}/Smileys/Persevering%20Face.webp`,
    [normalize("😞")]: `${BASE_URL}/Smileys/Disappointed%20Face.webp`,
    [normalize("😟")]: `${BASE_URL}/Smileys/Worried%20Face.webp`,
    [normalize("😵‍💫")]: `${BASE_URL}/Smileys/Face%20With%20Spiral%20Eyes.webp`,
    [normalize("🫠")]: `${BASE_URL}/Smileys/Melting%20Face.webp`,
    [normalize("🫡")]: `${BASE_URL}/Smileys/Saluting%20Face.webp`,
    [normalize("🫢")]: `${BASE_URL}/Smileys/Face%20With%20Open%20Eyes%20And%20Hand%20Over%20Mouth.webp`,
    [normalize("🫣")]: `${BASE_URL}/Smileys/Face%20With%20Peeking%20Eye.webp`,
    [normalize("🫤")]: `${BASE_URL}/Smileys/Face%20With%20Diagonal%20Mouth.webp`,
    [normalize("🫥")]: `${BASE_URL}/Smileys/Dotted%20Line%20Face.webp`,
    [normalize("🫨")]: `${BASE_URL}/Smileys/Shaking%20Face.webp`,
    [normalize("🤪")]: `${BASE_URL}/Smileys/Zany%20Face.webp`,
    [normalize("🥱")]: `${BASE_URL}/Smileys/Yawning%20Face.webp`,
    [normalize("😇")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Halo.webp`,
    [normalize("🥲")]: `${BASE_URL}/Smileys/Smiling%20Face%20With%20Tear.webp`,
    [normalize("🤣")]: `${BASE_URL}/Smileys/Rolling%20On%20The%20Floor%20Laughing.webp`,
    [normalize("😺")]: `${BASE_URL}/Smileys/Grinning%20Cat.webp`,
    [normalize("😸")]: `${BASE_URL}/Smileys/Grinning%20Cat%20With%20Smiling%20Eyes.webp`,
    [normalize("😹")]: `${BASE_URL}/Smileys/Cat%20With%20Tears%20Of%20Joy.webp`,
    [normalize("😻")]: `${BASE_URL}/Smileys/Smiling%20Cat%20With%20Heart%20Eyes.webp`,
    [normalize("😼")]: `${BASE_URL}/Smileys/Cat%20With%20Wry%20Smile.webp`,
    [normalize("😽")]: `${BASE_URL}/Smileys/Kissing%20Cat.webp`,
    [normalize("🙀")]: `${BASE_URL}/Smileys/Weary%20Cat.webp`,
    [normalize("😿")]: `${BASE_URL}/Smileys/Crying%20Cat.webp`,
    [normalize("😾")]: `${BASE_URL}/Smileys/Pouting%20Cat.webp`,
    [normalize("🙈")]: `${BASE_URL}/Smileys/See%20No%20Evil%20Monkey.webp`,
    [normalize("🙉")]: `${BASE_URL}/Smileys/Hear%20No%20Evil%20Monkey.webp`,
    [normalize("🙊")]: `${BASE_URL}/Smileys/Speak%20No%20Evil%20Monkey.webp`,
    [normalize("💋")]: `${BASE_URL}/Symbols/Kiss%20Mark.webp`,
    [normalize("😶‍🌫️")]: `${BASE_URL}/Smileys/Face%20In%20Clouds.webp`,
    [normalize("🤬")]: `${BASE_URL}/Smileys/Face%20With%20Symbols%20On%20Mouth.webp`,
    [normalize("🥹")]: `${BASE_URL}/Smileys/Face%20Holding%20Back%20Tears.webp`,
    [normalize("😮‍💨")]: `${BASE_URL}/Smileys/Face%20Exhaling.webp`,
    [normalize("😵")]: `${BASE_URL}/Smileys/Dizzy%20Face.webp`,
    [normalize("🫰")]: `${BASE_URL}/Smileys/Hand%20With%20Index%20Finger%20And%20Thumb%20Crossed.webp`,
    [normalize("👹")]: `${BASE_URL}/Smileys/Ogre.webp`,
    [normalize("👺")]: `${BASE_URL}/Smileys/Goblin.webp`,
    [normalize("☠️")]: `${BASE_URL}/Smileys/Skull%20And%20Crossbones.webp`,
    [normalize("😃")]: `${BASE_URL}/Smileys/Grinning%20Face%20With%20Big%20Eyes.webp`,
    [normalize("😨")]: `${BASE_URL}/Smileys/Fearful%20Face.webp`,
    [normalize("😰")]: `${BASE_URL}/Smileys/Anxious%20Face%20With%20Sweat.webp`,
    [normalize("😦")]: `${BASE_URL}/Smileys/Frowning%20Face%20With%20Open%20Mouth.webp`,
    [normalize("😧")]: `${BASE_URL}/Smileys/Anguished%20Face.webp`,
    [normalize("😩")]: `${BASE_URL}/Smileys/Weary%20Face.webp`,
    [normalize("🥵")]: `${BASE_URL}/Smileys/Hot%20Face.webp`,
    [normalize("😳")]: `${BASE_URL}/Smileys/Flushed%20Face.webp`,
    [normalize("☺️")]: `${BASE_URL}/Smileys/Smiling%20Face.webp`,
    

    // People
    [normalize("👍")]: `${BASE_URL}/People/Thumbs%20Up.webp`,
    [normalize("👎")]: `${BASE_URL}/People/Thumbs%20Down.webp`,
    [normalize("👏")]: `${BASE_URL}/People/Clapping%20Hands.webp`,
    [normalize("👋")]: `${BASE_URL}/People/Waving%20Hand.webp`,
    [normalize("❤️")]: `${BASE_URL}/Symbols/Red%20Heart.webp`,
    [normalize("💔")]: `${BASE_URL}/Symbols/Broken%20Heart.webp`,
    [normalize("🔥")]: `${BASE_URL}/Animals%20and%20Nature/Fire.webp`,
    [normalize("✨")]: `${BASE_URL}/Activity/Sparkles.webp`,
    [normalize("🎉")]: `${BASE_URL}/Activity/Party%20Popper.webp`,
    [normalize("💩")]: `${BASE_URL}/Smileys/Pile%20Of%20Poo.webp`,
    [normalize("🤡")]: `${BASE_URL}/Smileys/Clown%20Face.webp`,
    [normalize("👻")]: `${BASE_URL}/Smileys/Ghost.webp`,
    [normalize("💀")]: `${BASE_URL}/Smileys/Skull.webp`,
    [normalize("👽")]: `${BASE_URL}/Smileys/Alien.webp`,
    [normalize("👾")]: `${BASE_URL}/Smileys/Alien%20Monster.webp`,
    [normalize("🤖")]: `${BASE_URL}/Smileys/Robot.webp`,
    [normalize("🎃")]: `${BASE_URL}/Activity/Jack%20O%20Lantern.webp`,
    [normalize("👶")]: `${BASE_URL}/People/Baby.webp`,
    [normalize("👀")]: `${BASE_URL}/People/Eyes.webp`,
    [normalize("👅")]: `${BASE_URL}/People/Tongue.webp`,
    [normalize("👄")]: `${BASE_URL}/People/Mouth.webp`,
    [normalize("👃")]: `${BASE_URL}/People/Nose.webp`,
    [normalize("👂")]: `${BASE_URL}/People/Ear.webp`,
    [normalize("🦷")]: `${BASE_URL}/People/Tooth.webp`,
    [normalize("🦴")]: `${BASE_URL}/People/Bone.webp`,
    [normalize("🦶")]: `${BASE_URL}/People/Foot.webp`,
    [normalize("🦵")]: `${BASE_URL}/People/Leg.webp`,
    [normalize("👣")]: `${BASE_URL}/People/Footprints.webp`,
    [normalize("🐾")]: `${BASE_URL}/Animals%20and%20Nature/Paw%20Prints.webp`,
    [normalize("🤲")]: `${BASE_URL}/People/Palms%20Up%20Together.webp`,
    [normalize("👐")]: `${BASE_URL}/People/Open%20Hands.webp`,
    [normalize("🙌")]: `${BASE_URL}/People/Raising%20Hands.webp`,
    [normalize("✊")]: `${BASE_URL}/People/Raised%20Fist.webp`,
    [normalize("👊")]: `${BASE_URL}/People/Oncoming%20Fist.webp`,
    [normalize("🤛")]: `${BASE_URL}/People/Left%20Facing%20Fist.webp`,
    [normalize("🤜")]: `${BASE_URL}/People/Right%20Facing%20Fist.webp`,
    [normalize("🤌")]: `${BASE_URL}/People/Pinched%20Fingers.webp`,
    [normalize("🤏")]: `${BASE_URL}/People/Pinching%20Hand.webp`,
    [normalize("🫳")]: `${BASE_URL}/People/Palm%20Down%20Hand.webp`,
    [normalize("🫴")]: `${BASE_URL}/People/Palm%20Up%20Hand.webp`,
    [normalize("🫵")]: `${BASE_URL}/People/Index%20Pointing%20At%20The%20Viewer.webp`,
    [normalize("🫶")]: `${BASE_URL}/People/Heart%20Hands.webp`,
    [normalize("🫂")]: `${BASE_URL}/People/People%20Hugging.webp`,
    [normalize("🤷")]: `${BASE_URL}/People/Person%20Shrugging.webp`,
    [normalize("🤦")]: `${BASE_URL}/People/Person%20Facepalming.webp`,
    [normalize("💅")]: `${BASE_URL}/People/Nail%20Polish.webp`,
    [normalize("🎅")]: `${BASE_URL}/People/Santa%20Claus.webp`,
    [normalize("🤶")]: `${BASE_URL}/People/Mrs%20Claus.webp`,
    [normalize("🧑‍💻")]: `${BASE_URL}/People/Technologist.webp`,
    [normalize("🧟")]: `${BASE_URL}/People/Zombie.webp`,
    [normalize("🧛")]: `${BASE_URL}/People/Vampire.webp`,
    [normalize("🕺")]: `${BASE_URL}/People/Man%20Dancing.webp`,
    [normalize("💃")]: `${BASE_URL}/People/Woman%20Dancing.webp`,
    [normalize("🖕")]: `${BASE_URL}/People/Middle%20Finger.webp`,
    [normalize("🫦")]: `${BASE_URL}/People/Biting%20Lip.webp`,
    [normalize("🗣️")]: `${BASE_URL}/People/Speaking%20Head.webp`,
    [normalize("👤")]: `${BASE_URL}/People/Bust%20In%20Silhouette.webp`,
    [normalize("👥")]: `${BASE_URL}/People/Busts%20In%20Silhouette.webp`,
    

    // Hearts
    [normalize("💕")]: `${BASE_URL}/Symbols/Two%20Hearts.webp`,
    [normalize("💖")]: `${BASE_URL}/Symbols/Sparkling%20Heart.webp`,
    [normalize("💗")]: `${BASE_URL}/Symbols/Growing%20Heart.webp`,
    [normalize("💘")]: `${BASE_URL}/Symbols/Heart%20With%20Arrow.webp`,
    [normalize("💝")]: `${BASE_URL}/Symbols/Heart%20With%20Ribbon.webp`,
    [normalize("💞")]: `${BASE_URL}/Symbols/Revolving%20Hearts.webp`,
    [normalize("💓")]: `${BASE_URL}/Symbols/Beating%20Heart.webp`,
    [normalize("🖤")]: `${BASE_URL}/Symbols/Black%20Heart.webp`,
    [normalize("🤍")]: `${BASE_URL}/Symbols/White%20Heart.webp`,
    [normalize("💜")]: `${BASE_URL}/Symbols/Purple%20Heart.webp`,
    [normalize("💙")]: `${BASE_URL}/Symbols/Blue%20Heart.webp`,
    [normalize("💚")]: `${BASE_URL}/Symbols/Green%20Heart.webp`,
    [normalize("💛")]: `${BASE_URL}/Symbols/Yellow%20Heart.webp`,
    [normalize("🧡")]: `${BASE_URL}/Symbols/Orange%20Heart.webp`,
    [normalize("🤎")]: `${BASE_URL}/Symbols/Brown%20Heart.webp`,
    [normalize("❤️‍🔥")]: `${BASE_URL}/Symbols/Heart%20On%20Fire.webp`,
    [normalize("❤️‍🩹")]: `${BASE_URL}/Symbols/Mending%20Heart.webp`,
    
    // Animals
    [normalize("🐶")]: `${BASE_URL}/Animals%20and%20Nature/Dog%20Face.webp`,
    [normalize("🐱")]: `${BASE_URL}/Animals%20and%20Nature/Cat%20Face.webp`,
    [normalize("🐭")]: `${BASE_URL}/Animals%20and%20Nature/Mouse%20Face.webp`,
    [normalize("🐹")]: `${BASE_URL}/Animals%20and%20Nature/Hamster.webp`,
    [normalize("🐰")]: `${BASE_URL}/Animals%20and%20Nature/Rabbit%20Face.webp`,
    [normalize("🦊")]: `${BASE_URL}/Animals%20and%20Nature/Fox.webp`,
    [normalize("🐻")]: `${BASE_URL}/Animals%20and%20Nature/Bear.webp`,
    [normalize("🐼")]: `${BASE_URL}/Animals%20and%20Nature/Panda.webp`,
    [normalize("🐨")]: `${BASE_URL}/Animals%20and%20Nature/Koala.webp`,
    [normalize("🐯")]: `${BASE_URL}/Animals%20and%20Nature/Tiger%20Face.webp`,
    [normalize("🦁")]: `${BASE_URL}/Animals%20and%20Nature/Lion.webp`,
    [normalize("🐮")]: `${BASE_URL}/Animals%20and%20Nature/Cow%20Face.webp`,
    [normalize("🐷")]: `${BASE_URL}/Animals%20and%20Nature/Pig%20Face.webp`,
    [normalize("🐸")]: `${BASE_URL}/Animals%20and%20Nature/Frog.webp`,
    [normalize("🐵")]: `${BASE_URL}/Animals%20and%20Nature/Monkey%20Face.webp`,
    [normalize("🙈")]: `${BASE_URL}/Animals%20and%20Nature/See-No-Evil%20Monkey.webp`,
    [normalize("🙉")]: `${BASE_URL}/Animals%20and%20Nature/Hear-No-Evil%20Monkey.webp`,
    [normalize("🙊")]: `${BASE_URL}/Animals%20and%20Nature/Speak-No-Evil%20Monkey.webp`,
    [normalize("🐔")]: `${BASE_URL}/Animals%20and%20Nature/Chicken.webp`,
    [normalize("🐧")]: `${BASE_URL}/Animals%20and%20Nature/Penguin.webp`,
    [normalize("🐦")]: `${BASE_URL}/Animals%20and%20Nature/Bird.webp`,
    [normalize("🦋")]: `${BASE_URL}/Animals%20and%20Nature/Butterfly.webp`,
    [normalize("🐛")]: `${BASE_URL}/Animals%20and%20Nature/Bug.webp`,
    [normalize("🐝")]: `${BASE_URL}/Animals%20and%20Nature/Honeybee.webp`,
    [normalize("🐙")]: `${BASE_URL}/Animals%20and%20Nature/Octopus.webp`,
    [normalize("🦄")]: `${BASE_URL}/Animals%20and%20Nature/Unicorn.webp`,
    [normalize("🐻‍❄️")]: `${BASE_URL}/Animals%20and%20Nature/Polar%20Bear.webp`,
    [normalize("🦔")]: `${BASE_URL}/Animals%20and%20Nature/Hedgehog.webp`,
    [normalize("🦦")]: `${BASE_URL}/Animals%20and%20Nature/Seal.webp`,
    [normalize("🦧")]: `${BASE_URL}/Animals%20and%20Nature/Gorilla.webp`,
    [normalize("🐂")]: `${BASE_URL}/Animals%20and%20Nature/Ox.webp`,
    [normalize("🦬")]: `${BASE_URL}/Animals%20and%20Nature/Bison.webp`,
    [normalize("🐴")]: `${BASE_URL}/Animals%20and%20Nature/Horse%20Face.webp`,
    [normalize("🐎")]: `${BASE_URL}/Animals%20and%20Nature/Horse.webp`,
    [normalize("🦓")]: `${BASE_URL}/Animals%20and%20Nature/Zebra.webp`,
    [normalize("🦒")]: `${BASE_URL}/Animals%20and%20Nature/Giraffe.webp`,
    [normalize("🦙")]: `${BASE_URL}/Animals%20and%20Nature/Llama.webp`,
    [normalize("🦘")]: `${BASE_URL}/Animals%20and%20Nature/Kangaroo.webp`,
    [normalize("🦝")]: `${BASE_URL}/Animals%20and%20Nature/Raccoon.webp`,
    [normalize("🐕")]: `${BASE_URL}/Animals%20and%20Nature/Dog%20Face.webp`,
    [normalize("🐈")]: `${BASE_URL}/Animals%20and%20Nature/Cat.webp`,
    [normalize("🐈‍⬛")]: `${BASE_URL}/Animals%20and%20Nature/Black%20Cat.webp`,
    [normalize("🐓")]: `${BASE_URL}/Animals%20and%20Nature/Chicken.webp`,
    [normalize("🦃")]: `${BASE_URL}/Animals%20and%20Nature/Turkey.webp`,
    [normalize("🦚")]: `${BASE_URL}/Animals%20and%20Nature/Flamingo.webp`,
    [normalize("🦜")]: `${BASE_URL}/Animals%20and%20Nature/Parrot.webp`,
    [normalize("🦢")]: `${BASE_URL}/Animals%20and%20Nature/Swan.webp`,
    [normalize("🦩")]: `${BASE_URL}/Animals%20and%20Nature/Flamingo.webp`,
    [normalize("🦉")]: `${BASE_URL}/Animals%20and%20Nature/Owl.webp`,
    [normalize("🦅")]: `${BASE_URL}/Animals%20and%20Nature/Dove.webp`,
    [normalize("🦆")]: `${BASE_URL}/Animals%20and%20Nature/Duck.webp`,
    [normalize("🐥")]: `${BASE_URL}/Animals%20and%20Nature/Front%20Facing%20Baby%20Chick.webp`,
    [normalize("🐤")]: `${BASE_URL}/Animals%20and%20Nature/Baby%20Chick.webp`,
    [normalize("🐣")]: `${BASE_URL}/Animals%20and%20Nature/Hatching%20Chick.webp`,
    [normalize("🦇")]: `${BASE_URL}/Animals%20and%20Nature/Bat.webp`,
    [normalize("🐺")]: `${BASE_URL}/Animals%20and%20Nature/Parrot.webp`,
    [normalize("🐗")]: `${BASE_URL}/Animals%20and%20Nature/Bison.webp`,
    [normalize("🐴")]: `${BASE_URL}/Animals%20and%20Nature/Horse%20Face.webp`,
    [normalize("🦌")]: `${BASE_URL}/Animals%20and%20Nature/Deer.webp`,
    [normalize("🐘")]: `${BASE_URL}/Animals%20and%20Nature/Gorilla.webp`,
    [normalize("🐪")]: `${BASE_URL}/Animals%20and%20Nature/Llama.webp`,
    [normalize("🐑")]: `${BASE_URL}/Animals%20and%20Nature/Koala.webp`,
    [normalize("🐐")]: `${BASE_URL}/Animals%20and%20Nature/Gorilla.webp`,
    [normalize("🐆")]: `${BASE_URL}/Animals%20and%20Nature/Leopard.webp`,
    [normalize("🐅")]: `${BASE_URL}/Animals%20and%20Nature/Tiger.webp`,
    [normalize("🐄")]: `${BASE_URL}/Animals%20and%20Nature/Cow.webp`,
    [normalize("🐖")]: `${BASE_URL}/Animals%20and%20Nature/Pig%20Face.webp`,
    [normalize("🐇")]: `${BASE_URL}/Animals%20and%20Nature/Rabbit.webp`,
    [normalize("🦎")]: `${BASE_URL}/Animals%20and%20Nature/T%20Rex.webp`,
    [normalize("🐍")]: `${BASE_URL}/Animals%20and%20Nature/Snake.webp`,
    [normalize("🐢")]: `${BASE_URL}/Animals%20and%20Nature/Turtle.webp`,
    [normalize("🐉")]: `${BASE_URL}/Animals%20and%20Nature/T%20Rex.webp`,
    [normalize("🐲")]: `${BASE_URL}/Animals%20and%20Nature/Sauropod.webp`,
    [normalize("🦕")]: `${BASE_URL}/Animals%20and%20Nature/Sauropod.webp`,
    [normalize("🦖")]: `${BASE_URL}/Animals%20and%20Nature/T%20Rex.webp`,
    [normalize("🐳")]: `${BASE_URL}/Animals%20and%20Nature/Spouting%20Whale.webp`,
    [normalize("🐠")]: `${BASE_URL}/Animals%20and%20Nature/Tropical%20Fish.webp`,
    [normalize("🐟")]: `${BASE_URL}/Animals%20and%20Nature/Fish.webp`,
    [normalize("🦐")]: `${BASE_URL}/Animals%20and%20Nature/Shrimp.webp`,
    [normalize("🦑")]: `${BASE_URL}/Animals%20and%20Nature/Squid.webp`,
    [normalize("🦞")]: `${BASE_URL}/Animals%20and%20Nature/Lobster.webp`,
    [normalize("🐌")]: `${BASE_URL}/Animals%20and%20Nature/Snail.webp`,
    [normalize("🦗")]: `${BASE_URL}/Animals%20and%20Nature/Cricket.webp`,
    [normalize("🦟")]: `${BASE_URL}/Animals%20and%20Nature/Mosquito.webp`,
    [normalize("🪳")]: `${BASE_URL}/Animals%20and%20Nature/Cockroach.webp`,
    [normalize("🪲")]: `${BASE_URL}/Animals%20and%20Nature/Beetle.webp`,
    [normalize("🐞")]: `${BASE_URL}/Animals%20and%20Nature/Lady%20Beetle.webp`,
    [normalize("🐜")]: `${BASE_URL}/Animals%20and%20Nature/Ant.webp`,
    [normalize("🕷️")]: `${BASE_URL}/Animals%20and%20Nature/Spider.webp`,
    [normalize("🕸️")]: `${BASE_URL}/Animals%20and%20Nature/Spider%20Web.webp`,
    [normalize("🦠")]: `${BASE_URL}/Animals%20and%20Nature/Microbe.webp`,
    [normalize("🌸")]: `${BASE_URL}/Animals%20and%20Nature/Cherry%20Blossom.webp`,
    [normalize("💮")]: `${BASE_URL}/Animals%20and%20Nature/Blossom.webp`,
    [normalize("🌹")]: `${BASE_URL}/Animals%20and%20Nature/Rose.webp`,
    [normalize("🌺")]: `${BASE_URL}/Animals%20and%20Nature/Hibiscus.webp`,
    [normalize("🌻")]: `${BASE_URL}/Animals%20and%20Nature/Rosette.webp`,
    [normalize("🌷")]: `${BASE_URL}/Animals%20and%20Nature/Tulip.webp`,
    [normalize("💐")]: `${BASE_URL}/Animals%20and%20Nature/Bouquet.webp`,
    [normalize("🍀")]: `${BASE_URL}/Animals%20and%20Nature/Four%20Leaf%20Clover.webp`,
    [normalize("☘️")]: `${BASE_URL}/Animals%20and%20Nature/Shamrock.webp`,
    [normalize("🌿")]: `${BASE_URL}/Animals%20and%20Nature/Herb.webp`,
    [normalize("🌱")]: `${BASE_URL}/Animals%20and%20Nature/Seedling.webp`,
    [normalize("🌲")]: `${BASE_URL}/Animals%20and%20Nature/Evergreen%20Tree.webp`,
    [normalize("🌳")]: `${BASE_URL}/Animals%20and%20Nature/Deciduous%20Tree.webp`,
    [normalize("🌴")]: `${BASE_URL}/Animals%20and%20Nature/Palm%20Tree.webp`,
    [normalize("🌵")]: `${BASE_URL}/Animals%20and%20Nature/Cactus.webp`,
    [normalize("☀️")]: `${BASE_URL}/Animals%20and%20Nature/Sun.webp`,
    [normalize("🌞")]: `${BASE_URL}/Animals%20and%20Nature/Sun%20With%20Face.webp`,
    [normalize("🌝")]: `${BASE_URL}/Animals%20and%20Nature/Full%20Moon%20Face.webp`,
    [normalize("🌛")]: `${BASE_URL}/Animals%20and%20Nature/First%20Quarter%20Moon%20Face.webp`,
    [normalize("🌜")]: `${BASE_URL}/Animals%20and%20Nature/Last%20Quarter%20Moon%20Face.webp`,
    [normalize("🌚")]: `${BASE_URL}/Animals%20and%20Nature/New%20Moon%20Face.webp`,
    [normalize("🌕")]: `${BASE_URL}/Animals%20and%20Nature/Full%20Moon.webp`,
    [normalize("🌑")]: `${BASE_URL}/Animals%20and%20Nature/New%20Moon.webp`,
    [normalize("🌒")]: `${BASE_URL}/Animals%20and%20Nature/Waxing%20Crescent%20Moon.webp`,
    [normalize("🌓")]: `${BASE_URL}/Animals%20and%20Nature/First%20Quarter%20Moon.webp`,
    [normalize("🌔")]: `${BASE_URL}/Animals%20and%20Nature/Waxing%20Gibbous%20Moon.webp`,
    [normalize("🌘")]: `${BASE_URL}/Animals%20and%20Nature/Waning%20Crescent%20Moon.webp`,
    [normalize("🌗")]: `${BASE_URL}/Animals%20and%20Nature/Last%20Quarter%20Moon.webp`,
    [normalize("⭐")]: `${BASE_URL}/Animals%20and%20Nature/Star.webp`,
    [normalize("🌟")]: `${BASE_URL}/Animals%20and%20Nature/Glowing%20Star.webp`,
    [normalize("⚡")]: `${BASE_URL}/Animals%20and%20Nature/High%20Voltage.webp`,
    [normalize("❄️")]: `${BASE_URL}/Animals%20and%20Nature/Snowflake.webp`,
    [normalize("☃️")]: `${BASE_URL}/Animals%20and%20Nature/Snowman.webp`,
    [normalize("⛄")]: `${BASE_URL}/Animals%20and%20Nature/Snowman%20Without%20Snow.webp`,
    [normalize("☁️")]: `${BASE_URL}/Animals%20and%20Nature/Cloud.webp`,
    [normalize("⛅")]: `${BASE_URL}/Animals%20and%20Nature/Sun%20Behind%20Cloud.webp`,
    [normalize("🌤️")]: `${BASE_URL}/Animals%20and%20Nature/Sun%20Behind%20Small%20Cloud.webp`,
    [normalize("🌥️")]: `${BASE_URL}/Animals%20and%20Nature/Sun%20Behind%20Large%20Cloud.webp`,
    [normalize("🌦️")]: `${BASE_URL}/Animals%20and%20Nature/Sun%20Behind%20Rain%20Cloud.webp`,
    [normalize("🌧️")]: `${BASE_URL}/Animals%20and%20Nature/Cloud%20With%20Rain.webp`,
    [normalize("🌩️")]: `${BASE_URL}/Animals%20and%20Nature/Cloud%20With%20Lightning.webp`,
    [normalize("⛈️")]: `${BASE_URL}/Animals%20and%20Nature/Cloud%20With%20Lightning%20And%20Rain.webp`,
    [normalize("🌨️")]: `${BASE_URL}/Animals%20and%20Nature/Cloud%20With%20Snow.webp`,
    [normalize("🌈")]: `${BASE_URL}/Animals%20and%20Nature/Rainbow.webp`,
    

    // Food
    [normalize("🍎")]: `${BASE_URL}/Food%20and%20Drink/Red%20Apple.webp`,
    [normalize("🍕")]: `${BASE_URL}/Food%20and%20Drink/Pizza.webp`,
    [normalize("🍔")]: `${BASE_URL}/Food%20and%20Drink/Hamburger.webp`,
    [normalize("🍟")]: `${BASE_URL}/Food%20and%20Drink/French%20Fries.webp`,
    [normalize("🍩")]: `${BASE_URL}/Food%20and%20Drink/Doughnut.webp`,
    [normalize("🍰")]: `${BASE_URL}/Food%20and%20Drink/Shortcake.webp`,
    [normalize("🎂")]: `${BASE_URL}/Food%20and%20Drink/Birthday%20Cake.webp`,
    [normalize("🍦")]: `${BASE_URL}/Food%20and%20Drink/Soft%20Ice%20Cream.webp`,
    [normalize("🍺")]: `${BASE_URL}/Food%20and%20Drink/Beer%20Mug.webp`,
    [normalize("☕")]: `${BASE_URL}/Food%20and%20Drink/Hot%20Beverage.webp`,
    [normalize("🍌")]: `${BASE_URL}/Food%20and%20Drink/Banana.webp`,
    [normalize("🍓")]: `${BASE_URL}/Food%20and%20Drink/Strawberry.webp`,
    [normalize("🍪")]: `${BASE_URL}/Food%20and%20Drink/Cookie.webp`,
    [normalize("🍫")]: `${BASE_URL}/Food%20and%20Drink/Chocolate%20Bar.webp`,
    [normalize("🍭")]: `${BASE_URL}/Food%20and%20Drink/Lollipop.webp`,
    [normalize("🍮")]: `${BASE_URL}/Food%20and%20Drink/Custard.webp`,
    [normalize("🍡")]: `${BASE_URL}/Food%20and%20Drink/Dango.webp`,
    [normalize("🍿")]: `${BASE_URL}/Food%20and%20Drink/Popcorn.webp`,
    [normalize("🌭")]: `${BASE_URL}/Food%20and%20Drink/Hot%20Dog.webp`,
    [normalize("🥓")]: `${BASE_URL}/Food%20and%20Drink/Meat%20On%20Bone.webp`,
    [normalize("🍖")]: `${BASE_URL}/Food%20and%20Drink/Poultry%20Leg.webp`,
    [normalize("🍗")]: `${BASE_URL}/Food%20and%20Drink/Poultry%20Leg.webp`,
    [normalize("🍳")]: `${BASE_URL}/Food%20and%20Drink/Cooking.webp`,
    [normalize("🥞")]: `${BASE_URL}/Food%20and%20Drink/Pancakes.webp`,
    [normalize("🧁")]: `${BASE_URL}/Food%20and%20Drink/Cupcake.webp`,
    [normalize("🥧")]: `${BASE_URL}/Food%20and%20Drink/Pie.webp`,
    [normalize("🍣")]: `${BASE_URL}/Food%20and%20Drink/Sushi.webp`,
    [normalize("🍱")]: `${BASE_URL}/Food%20and%20Drink/Bento%20Box.webp`,
    [normalize("🍙")]: `${BASE_URL}/Food%20and%20Drink/Rice%20Ball.webp`,
    [normalize("🍘")]: `${BASE_URL}/Food%20and%20Drink/Rice%20Cracker.webp`,
    [normalize("🍥")]: `${BASE_URL}/Food%20and%20Drink/Fish%20Cake%20With%20Swirl.webp`,
    [normalize("🥛")]: `${BASE_URL}/Food%20and%20Drink/Glass%20Of%20Milk.webp`,
    [normalize("🍼")]: `${BASE_URL}/Food%20and%20Drink/Baby%20Bottle.webp`,
    [normalize("🧃")]: `${BASE_URL}/Food%20and%20Drink/Beverage%20Box.webp`,
    [normalize("🧉")]: `${BASE_URL}/Food%20and%20Drink/Mate.webp`,
    [normalize("🍷")]: `${BASE_URL}/Food%20and%20Drink/Wine%20Glass.webp`,
    [normalize("🍸")]: `${BASE_URL}/Food%20and%20Drink/Cocktail%20Glass.webp`,
    [normalize("🍹")]: `${BASE_URL}/Food%20and%20Drink/Tropical%20Drink.webp`,
    [normalize("🥃")]: `${BASE_URL}/Food%20and%20Drink/Tumbler%20Glass.webp`,
    [normalize("🥂")]: `${BASE_URL}/Food%20and%20Drink/Clinking%20Glasses.webp`,
    [normalize("🍾")]: `${BASE_URL}/Food%20and%20Drink/Bottle%20With%20Popping%20Cork.webp`,
    [normalize("🧋")]: `${BASE_URL}/Food%20and%20Drink/Bubble%20Tea.webp`,
    [normalize("🥤")]: `${BASE_URL}/Food%20and%20Drink/Cup%20With%20Straw.webp`,
    [normalize("🌮")]: `${BASE_URL}/Food%20and%20Drink/Taco.webp`,
    [normalize("🥪")]: `${BASE_URL}/Food%20and%20Drink/Sandwich.webp`,
    [normalize("🥙")]: `${BASE_URL}/Food%20and%20Drink/Stuffed%20Flatbread.webp`,
    [normalize("🥨")]: `${BASE_URL}/Food%20and%20Drink/Pretzel.webp`,
    [normalize("🍢")]: `${BASE_URL}/Food%20and%20Drink/Oden.webp`,
    [normalize("🍽️")]: `${BASE_URL}/Food%20and%20Drink/Fork%20And%20Knife%20With%20Plate.webp`,
    [normalize("🥫")]: `${BASE_URL}/Food%20and%20Drink/Canned%20Food.webp`,
    [normalize("🫗")]: `${BASE_URL}/Food%20and%20Drink/Pouring%20Liquid.webp`,
    

    // Activities
    [normalize("⚽")]: `${BASE_URL}/Activity/Soccer%20Ball.webp`,
    [normalize("🏀")]: `${BASE_URL}/Activity/Basketball.webp`,
    [normalize("🏈")]: `${BASE_URL}/Activity/American%20Football.webp`,
    [normalize("🎮")]: `${BASE_URL}/Activity/Video%20Game.webp`,
    [normalize("🎲")]: `${BASE_URL}/Activity/Game%20Die.webp`,
    [normalize("🎯")]: `${BASE_URL}/Activity/Direct%20Hit.webp`,
    [normalize("🎵")]: `${BASE_URL}/Activity/Musical%20Note.webp`,
    [normalize("🎶")]: `${BASE_URL}/Activity/Musical%20Notes.webp`,
    [normalize("🎁")]: `${BASE_URL}/Activity/Wrapped%20Gift.webp`,
    [normalize("🎀")]: `${BASE_URL}/Activity/Ribbon.webp`,
    [normalize("🏆")]: `${BASE_URL}/Activity/Trophy.webp`,
    [normalize("🥇")]: `${BASE_URL}/Activity/1st%20Place%20Medal.webp`,
    [normalize("🥈")]: `${BASE_URL}/Activity/2nd%20Place%20Medal.webp`,
    [normalize("🥉")]: `${BASE_URL}/Activity/3rd%20Place%20Medal.webp`,
    [normalize("🎖️")]: `${BASE_URL}/Activity/Military%20Medal.webp`,
    [normalize("🏅")]: `${BASE_URL}/Activity/Sports%20Medal.webp`,
    [normalize("🎫")]: `${BASE_URL}/Activity/Ticket.webp`,
    [normalize("🎟️")]: `${BASE_URL}/Activity/Admission%20Tickets.webp`,
    [normalize("🎨")]: `${BASE_URL}/Activity/Artist%20Palette.webp`,
    [normalize("🎭")]: `${BASE_URL}/Activity/Performing%20Arts.webp`,
    [normalize("🪄")]: `${BASE_URL}/Activity/Magic%20Wand.webp`,
    [normalize("🔮")]: `${BASE_URL}/Activity/Crystal%20Ball.webp`,
    [normalize("🪩")]: `${BASE_URL}/Activity/Mirror%20Ball.webp`,
    [normalize("🎈")]: `${BASE_URL}/Activity/Balloon.webp`,
    [normalize("🎊")]: `${BASE_URL}/Activity/Confetti%20Ball.webp`,
    [normalize("🧨")]: `${BASE_URL}/Activity/Firecracker.webp`,
    [normalize("🎆")]: `${BASE_URL}/Activity/Fireworks.webp`,
    [normalize("🎇")]: `${BASE_URL}/Activity/Sparkler.webp`,
    [normalize("🎄")]: `${BASE_URL}/Activity/Christmas%20Tree.webp`,
    


    // Objects
    [normalize("💡")]: `${BASE_URL}/Objects/Light%20Bulb.webp`,
    [normalize("💰")]: `${BASE_URL}/Objects/Money%20Bag.webp`,
    [normalize("💎")]: `${BASE_URL}/Objects/Gem%20Stone.webp`,
    [normalize("🔔")]: `${BASE_URL}/Objects/Bell.webp`,
    [normalize("📱")]: `${BASE_URL}/Objects/Mobile%20Phone.webp`,
    [normalize("💻")]: `${BASE_URL}/Objects/Laptop.webp`,
    [normalize("⌚")]: `${BASE_URL}/Objects/Watch.webp`,
    [normalize("📷")]: `${BASE_URL}/Objects/Camera.webp`,
    [normalize("🔑")]: `${BASE_URL}/Objects/Key.webp`,
    [normalize("✉️")]: `${BASE_URL}/Objects/Incoming%20Envelope.webp`,
    [normalize("📨")]: `${BASE_URL}/Objects/Incoming%20Envelope.webp`,
    [normalize("📩")]: `${BASE_URL}/Objects/Outbox%20Tray.webp`,
    [normalize("📤")]: `${BASE_URL}/Objects/Outbox%20Tray.webp`,
    [normalize("📥")]: `${BASE_URL}/Objects/Inbox%20Tray.webp`,
    [normalize("📜")]: `${BASE_URL}/Objects/Open%20Book.webp`,
    [normalize("📖")]: `${BASE_URL}/Objects/Open%20Book.webp`,
    [normalize("📚")]: `${BASE_URL}/Objects/Books.webp`,
    [normalize("📰")]: `${BASE_URL}/Objects/Newspaper.webp`,
    [normalize("📝")]: `${BASE_URL}/Objects/Memo.webp`,
    [normalize("✏️")]: `${BASE_URL}/Objects/Pencil.webp`,
    [normalize("📁")]: `${BASE_URL}/Objects/File%20Folder.webp`,
    [normalize("📂")]: `${BASE_URL}/Objects/Card%20Index%20Dividers.webp`,
    [normalize("🗓️")]: `${BASE_URL}/Objects/Tear%20Off%20Calendar.webp`,
    [normalize("📊")]: `${BASE_URL}/Objects/Bar%20Chart.webp`,
    [normalize("📈")]: `${BASE_URL}/Objects/Chart%20Increasing.webp`,
    [normalize("📉")]: `${BASE_URL}/Objects/Chart%20Decreasing.webp`,
    [normalize("🖨️")]: `${BASE_URL}/Objects/Printer.webp`,
    [normalize("⌨️")]: `${BASE_URL}/Objects/Keyboard.webp`,
    [normalize("🔍")]: `${BASE_URL}/Objects/Magnifying%20Glass%20Tilted%20Left.webp`,
    [normalize("🔎")]: `${BASE_URL}/Objects/Magnifying%20Glass%20Tilted%20Right.webp`,
    [normalize("🔬")]: `${BASE_URL}/Objects/Microscope.webp`,
    [normalize("🔭")]: `${BASE_URL}/Objects/Telescope.webp`,
    [normalize("📺")]: `${BASE_URL}/Objects/Television.webp`,
    [normalize("🎤")]: `${BASE_URL}/Objects/Microphone.webp`,
    [normalize("🎙️")]: `${BASE_URL}/Objects/Studio%20Microphone.webp`,
    [normalize("📞")]: `${BASE_URL}/Objects/Telephone%20Receiver.webp`,
    [normalize("☎️")]: `${BASE_URL}/Objects/Telephone.webp`,
    [normalize("📲")]: `${BASE_URL}/Objects/Mobile%20Phone%20With%20Arrow.webp`,
    [normalize("💳")]: `${BASE_URL}/Objects/Identification%20Card.webp`,
    [normalize("💸")]: `${BASE_URL}/Objects/Money%20With%20Wings.webp`,
    [normalize("🪙")]: `${BASE_URL}/Objects/Coin.webp`,
    [normalize("💼")]: `${BASE_URL}/Objects/Briefcase.webp`,
    [normalize("👜")]: `${BASE_URL}/Objects/Handbag.webp`,
    [normalize("👛")]: `${BASE_URL}/Objects/Purse.webp`,
    [normalize("🛍️")]: `${BASE_URL}/Objects/Shopping%20Bags.webp`,
    [normalize("🛒")]: `${BASE_URL}/Objects/Shopping%20Cart.webp`,
    [normalize("🧳")]: `${BASE_URL}/Objects/Luggage.webp`,
    [normalize("👑")]: `${BASE_URL}/Objects/Crown.webp`,
    [normalize("🎓")]: `${BASE_URL}/Objects/Graduation%20Cap.webp`,
    [normalize("🪖")]: `${BASE_URL}/Objects/Military%20Helmet.webp`,
    [normalize("🎩")]: `${BASE_URL}/Objects/Top%20Hat.webp`,
    [normalize("👠")]: `${BASE_URL}/Objects/High%20Heeled%20Shoe.webp`,
    [normalize("💊")]: `${BASE_URL}/Objects/Pill.webp`,
    [normalize("💉")]: `${BASE_URL}/Objects/Syringe.webp`,
    [normalize("🩺")]: `${BASE_URL}/Objects/Stethoscope.webp`,
    [normalize("🌡️")]: `${BASE_URL}/Objects/Thermometer.webp`,
    [normalize("🧪")]: `${BASE_URL}/Objects/Test%20Tube.webp`,
    [normalize("🧲")]: `${BASE_URL}/Objects/Abacus.webp`,
    [normalize("🧯")]: `${BASE_URL}/Objects/Toolbox.webp`,
    [normalize("🔗")]: `${BASE_URL}/Objects/Locked%20With%20Key.webp`,
    [normalize("🔒")]: `${BASE_URL}/Objects/Locked%20With%20Key.webp`,
    [normalize("🗝️")]: `${BASE_URL}/Objects/Old%20Key.webp`,
    [normalize("💣")]: `${BASE_URL}/Objects/Bomb.webp`,
    [normalize("⚰️")]: `${BASE_URL}/Objects/Coffin.webp`,
    [normalize("🗳️")]: `${BASE_URL}/Objects/Ballot%20Box%20With%20Ballot.webp`,
    [normalize("📢")]: `${BASE_URL}/Objects/Megaphone.webp`,
    [normalize("🎗️")]: `${BASE_URL}/Objects/Reminder%20Ribbon.webp`,
    [normalize("🧻")]: `${BASE_URL}/Objects/Roll%20Of%20Paper.webp`,
    [normalize("🧽")]: `${BASE_URL}/Objects/Sponge.webp`,
    [normalize("🧼")]: `${BASE_URL}/Objects/Soap.webp`,
    [normalize("⏳")]: `${BASE_URL}/Objects/Hourglass%20Not%20Done.webp`,
    [normalize("⌛")]: `${BASE_URL}/Objects/Hourglass%20Done.webp`,
    [normalize("🎬")]: `${BASE_URL}/Objects/Clapper%20Board.webp`,
    [normalize("🎵")]: `${BASE_URL}/Objects/Musical%20Note.webp`,
    [normalize("🎶")]: `${BASE_URL}/Objects/Musical%20Notes.webp`,
    

    // Travel & Places
    [normalize("🌈")]: `${BASE_URL}/Travel%20and%20Places/Rainbow.webp`,
    [normalize("⭐")]: `${BASE_URL}/Travel%20and%20Places/Star.webp`,
    [normalize("🌙")]: `${BASE_URL}/Travel%20and%20Places/Crescent%20Moon.webp`,
    [normalize("☀️")]: `${BASE_URL}/Travel%20and%20Places/Sun.webp`,
    [normalize("⚡")]: `${BASE_URL}/Travel%20and%20Places/High%20Voltage.webp`,
    [normalize("❄️")]: `${BASE_URL}/Travel%20and%20Places/Snowflake.webp`,
    [normalize("💧")]: `${BASE_URL}/Travel%20and%20Places/Droplet.webp`,
    [normalize("🌊")]: `${BASE_URL}/Travel%20and%20Places/Water%20Wave.webp`,
    [normalize("🎄")]: `${BASE_URL}/Travel%20and%20Places/Christmas%20Tree.webp`,
    [normalize("🌹")]: `${BASE_URL}/Animals%20and%20Nature/Rose.webp`,
    [normalize("🌸")]: `${BASE_URL}/Animals%20and%20Nature/Cherry%20Blossom.webp`,
    [normalize("🌺")]: `${BASE_URL}/Animals%20and%20Nature/Hibiscus.webp`,
    
    // Gestures
    [normalize("✌️")]: `${BASE_URL}/People/Victory%20Hand.webp`,
    [normalize("🤞")]: `${BASE_URL}/People/Crossed%20Fingers.webp`,
    [normalize("🤟")]: `${BASE_URL}/People/Love-You%20Gesture.webp`,
    [normalize("🤘")]: `${BASE_URL}/People/Sign%20Of%20The%20Horns.webp`,
    [normalize("👌")]: `${BASE_URL}/People/Ok%20Hand.webp`,
    [normalize("👈")]: `${BASE_URL}/People/Backhand%20Index%20Pointing%20Left.webp`,
    [normalize("👉")]: `${BASE_URL}/People/Backhand%20Index%20Pointing%20Right.webp`,
    [normalize("👆")]: `${BASE_URL}/People/Backhand%20Index%20Pointing%20Up.webp`,
    [normalize("👇")]: `${BASE_URL}/People/Backhand%20Index%20Pointing%20Down.webp`,
    [normalize("☝️")]: `${BASE_URL}/People/Index%20Pointing%20Up.webp`,
    [normalize("✋")]: `${BASE_URL}/People/Raised%20Hand.webp`,
    [normalize("🤚")]: `${BASE_URL}/People/Raised%20Back%20Of%20Hand.webp`,
    [normalize("🖐️")]: `${BASE_URL}/People/Hand%20With%20Fingers%20Splayed.webp`,
    [normalize("🖖")]: `${BASE_URL}/People/Vulcan%20Salute.webp`,
    [normalize("🤙")]: `${BASE_URL}/People/Call%20Me%20Hand.webp`,
    [normalize("💪")]: `${BASE_URL}/People/Flexed%20Biceps.webp`,
    [normalize("🙏")]: `${BASE_URL}/People/Folded%20Hands.webp`,
    [normalize("🤝")]: `${BASE_URL}/People/Handshake.webp`,
    [normalize("✍️")]: `${BASE_URL}/People/Writing%20Hand.webp`,
    
    // Symbols
    [normalize("💯")]: `${BASE_URL}/Symbols/Hundred%20Points.webp`,
    [normalize("💢")]: `${BASE_URL}/Symbols/Anger%20Symbol.webp`,
    [normalize("💥")]: `${BASE_URL}/Symbols/Collision.webp`,
    [normalize("💫")]: `${BASE_URL}/Symbols/Dizzy.webp`,
    [normalize("💦")]: `${BASE_URL}/Symbols/Sweat%20Droplets.webp`,
    [normalize("💤")]: `${BASE_URL}/Symbols/Zzz.webp`,
    [normalize("💬")]: `${BASE_URL}/Symbols/Speech%20Balloon.webp`,
    [normalize("💭")]: `${BASE_URL}/Symbols/Thought%20Balloon.webp`,
    [normalize("❓")]: `${BASE_URL}/Symbols/Question%20Mark.webp`,
    [normalize("❗")]: `${BASE_URL}/Symbols/Exclamation%20Mark.webp`,
    [normalize("✅")]: `${BASE_URL}/Symbols/Check%20Mark%20Button.webp`,
    [normalize("❌")]: `${BASE_URL}/Symbols/Cross%20Mark.webp`,
    [normalize("‼️")]: `${BASE_URL}/Symbols/Double%20Exclamation%20Mark.webp`,
    [normalize("⁉️")]: `${BASE_URL}/Symbols/Exclamation%20Question%20Mark.webp`,
    [normalize("❕")]: `${BASE_URL}/Symbols/White%20Exclamation%20Mark.webp`,
    [normalize("❔")]: `${BASE_URL}/Symbols/White%20Question%20Mark.webp`,
    [normalize("✔️")]: `${BASE_URL}/Symbols/Check%20Mark.webp`,
    [normalize("☑️")]: `${BASE_URL}/Symbols/Check%20Box%20With%20Check.webp`,
    [normalize("🔝")]: `${BASE_URL}/Symbols/Top%20Arrow.webp`,
    [normalize("🆙")]: `${BASE_URL}/Symbols/Up%20Button.webp`,
    [normalize("🆕")]: `${BASE_URL}/Symbols/New%20Button.webp`,
    [normalize("🆓")]: `${BASE_URL}/Symbols/Free%20Button.webp`,
    [normalize("🆗")]: `${BASE_URL}/Symbols/Ok%20Button.webp`,
    [normalize("🆒")]: `${BASE_URL}/Symbols/Cool%20Button.webp`,
    [normalize("🔞")]: `${BASE_URL}/Symbols/No%20One%20Under%20Eighteen.webp`,
    [normalize("💱")]: `${BASE_URL}/Symbols/Currency%20Exchange.webp`,
    [normalize("🛃")]: `${BASE_URL}/Symbols/Customs.webp`,
    [normalize("🛄")]: `${BASE_URL}/Symbols/Baggage%20Claim.webp`,
    [normalize("🛅")]: `${BASE_URL}/Symbols/Left%20Luggage.webp`,
    [normalize("🛂")]: `${BASE_URL}/Symbols/Passport%20Control.webp`,
    [normalize("🚹")]: `${BASE_URL}/Symbols/Mens%20Room.webp`,
    [normalize("🚺")]: `${BASE_URL}/Symbols/Womens%20Room.webp`,
    [normalize("🚼")]: `${BASE_URL}/Symbols/Baby%20Symbol.webp`,
    [normalize("💌")]: `${BASE_URL}/Symbols/Love%20Letter.webp`,
    [normalize("❣️")]: `${BASE_URL}/Symbols/Heart%20Exclamation.webp`,
    [normalize("💟")]: `${BASE_URL}/Symbols/Heart%20Decoration.webp`,
    [normalize("🗯️")]: `${BASE_URL}/Symbols/Right%20Anger%20Bubble.webp`,
    // Zodiac Signs
    [normalize("♈")]: `${BASE_URL}/Symbols/Aries.webp`,
    [normalize("♉")]: `${BASE_URL}/Symbols/Taurus.webp`,
    [normalize("♊")]: `${BASE_URL}/Symbols/Gemini.webp`,
    [normalize("♋")]: `${BASE_URL}/Symbols/Cancer.webp`,
    [normalize("♌")]: `${BASE_URL}/Symbols/Leo.webp`,
    [normalize("♍")]: `${BASE_URL}/Symbols/Virgo.webp`,
    [normalize("♎")]: `${BASE_URL}/Symbols/Libra.webp`,
    [normalize("♏")]: `${BASE_URL}/Symbols/Scorpio.webp`,
    [normalize("♐")]: `${BASE_URL}/Symbols/Sagittarius.webp`,
    [normalize("♑")]: `${BASE_URL}/Symbols/Capricorn.webp`,
    [normalize("♒")]: `${BASE_URL}/Symbols/Aquarius.webp`,
    [normalize("♓")]: `${BASE_URL}/Symbols/Pisces.webp`,
    [normalize("⛎")]: `${BASE_URL}/Symbols/Ophiuchus.webp`,
    

    // More Animals
    [normalize("🐍")]: `${BASE_URL}/Animals%20and%20Nature/Snake.webp`,
    [normalize("🐢")]: `${BASE_URL}/Animals%20and%20Nature/Turtle.webp`,
    [normalize("🦎")]: `${BASE_URL}/Animals%20and%20Nature/Lizard.webp`,
    [normalize("🐊")]: `${BASE_URL}/Animals%20and%20Nature/Crocodile.webp`,
    [normalize("🐳")]: `${BASE_URL}/Animals%20and%20Nature/Spouting%20Whale.webp`,
    [normalize("🐬")]: `${BASE_URL}/Animals%20and%20Nature/Dolphin.webp`,
    [normalize("🦈")]: `${BASE_URL}/Animals%20and%20Nature/Shark.webp`,
    [normalize("🐠")]: `${BASE_URL}/Animals%20and%20Nature/Tropical%20Fish.webp`,
    [normalize("🐟")]: `${BASE_URL}/Animals%20and%20Nature/Fish.webp`,
    [normalize("🐡")]: `${BASE_URL}/Animals%20and%20Nature/Blowfish.webp`,
    [normalize("🦐")]: `${BASE_URL}/Animals%20and%20Nature/Shrimp.webp`,
    [normalize("🦑")]: `${BASE_URL}/Animals%20and%20Nature/Squid.webp`,
    [normalize("🦀")]: `${BASE_URL}/Animals%20and%20Nature/Crab.webp`,
    [normalize("🐌")]: `${BASE_URL}/Animals%20and%20Nature/Snail.webp`,
    [normalize("🦗")]: `${BASE_URL}/Animals%20and%20Nature/Cricket.webp`,
    [normalize("🐞")]: `${BASE_URL}/Animals%20and%20Nature/Lady%20Beetle.webp`,
    [normalize("🦂")]: `${BASE_URL}/Animals%20and%20Nature/Scorpion.webp`,
    [normalize("🕷️")]: `${BASE_URL}/Animals%20and%20Nature/Spider.webp`,
    [normalize("🕸️")]: `${BASE_URL}/Animals%20and%20Nature/Spider%20Web.webp`,
    [normalize("🐺")]: `${BASE_URL}/Animals%20and%20Nature/Wolf.webp`,
    [normalize("🦝")]: `${BASE_URL}/Animals%20and%20Nature/Raccoon.webp`,
    [normalize("🐗")]: `${BASE_URL}/Animals%20and%20Nature/Boar.webp`,
    [normalize("🐴")]: `${BASE_URL}/Animals%20and%20Nature/Horse%20Face.webp`,
    [normalize("🦓")]: `${BASE_URL}/Animals%20and%20Nature/Zebra.webp`,
    [normalize("🦒")]: `${BASE_URL}/Animals%20and%20Nature/Giraffe.webp`,
    [normalize("🐘")]: `${BASE_URL}/Animals%20and%20Nature/Elephant.webp`,
    [normalize("🦛")]: `${BASE_URL}/Animals%20and%20Nature/Hippopotamus.webp`,
    [normalize("🐪")]: `${BASE_URL}/Animals%20and%20Nature/Camel.webp`,
    [normalize("🐫")]: `${BASE_URL}/Animals%20and%20Nature/Two-Hump%20Camel.webp`,
    [normalize("🦘")]: `${BASE_URL}/Animals%20and%20Nature/Kangaroo.webp`,
    [normalize("🐑")]: `${BASE_URL}/Animals%20and%20Nature/Ewe.webp`,
    [normalize("🐐")]: `${BASE_URL}/Animals%20and%20Nature/Goat.webp`,
    [normalize("🦌")]: `${BASE_URL}/Animals%20and%20Nature/Deer.webp`,
    [normalize("🐕")]: `${BASE_URL}/Animals%20and%20Nature/Dog.webp`,
    [normalize("🐩")]: `${BASE_URL}/Animals%20and%20Nature/Poodle.webp`,
    [normalize("🦮")]: `${BASE_URL}/Animals%20and%20Nature/Guide%20Dog.webp`,
    [normalize("🐈")]: `${BASE_URL}/Animals%20and%20Nature/Cat.webp`,
    [normalize("🐓")]: `${BASE_URL}/Animals%20and%20Nature/Rooster.webp`,
    [normalize("🦃")]: `${BASE_URL}/Animals%20and%20Nature/Turkey.webp`,
    [normalize("🦚")]: `${BASE_URL}/Animals%20and%20Nature/Peacock.webp`,
    [normalize("🦜")]: `${BASE_URL}/Animals%20and%20Nature/Parrot.webp`,
    [normalize("🦢")]: `${BASE_URL}/Animals%20and%20Nature/Swan.webp`,
    [normalize("🦩")]: `${BASE_URL}/Animals%20and%20Nature/Flamingo.webp`,
    [normalize("🦉")]: `${BASE_URL}/Animals%20and%20Nature/Owl.webp`,
    [normalize("🦅")]: `${BASE_URL}/Animals%20and%20Nature/Eagle.webp`,
    [normalize("🦆")]: `${BASE_URL}/Animals%20and%20Nature/Duck.webp`,
    [normalize("🐥")]: `${BASE_URL}/Animals%20and%20Nature/Front-Facing%20Baby%20Chick.webp`,
    [normalize("🐤")]: `${BASE_URL}/Animals%20and%20Nature/Baby%20Chick.webp`,
    [normalize("🐣")]: `${BASE_URL}/Animals%20and%20Nature/Hatching%20Chick.webp`,
    [normalize("🦇")]: `${BASE_URL}/Animals%20and%20Nature/Bat.webp`,
    [normalize("🐲")]: `${BASE_URL}/Animals%20and%20Nature/Dragon%20Face.webp`,
    [normalize("🐉")]: `${BASE_URL}/Animals%20and%20Nature/Dragon.webp`,
    
    // More Food
    [normalize("🍇")]: `${BASE_URL}/Food%20and%20Drink/Grapes.webp`,
    [normalize("🍈")]: `${BASE_URL}/Food%20and%20Drink/Melon.webp`,
    [normalize("🍉")]: `${BASE_URL}/Food%20and%20Drink/Watermelon.webp`,
    [normalize("🍊")]: `${BASE_URL}/Food%20and%20Drink/Tangerine.webp`,
    [normalize("🍋")]: `${BASE_URL}/Food%20and%20Drink/Lemon.webp`,
    [normalize("🍌")]: `${BASE_URL}/Food%20and%20Drink/Banana.webp`,
    [normalize("🍍")]: `${BASE_URL}/Food%20and%20Drink/Pineapple.webp`,
    [normalize("🥭")]: `${BASE_URL}/Food%20and%20Drink/Mango.webp`,
    [normalize("🍑")]: `${BASE_URL}/Food%20and%20Drink/Peach.webp`,
    [normalize("🍒")]: `${BASE_URL}/Food%20and%20Drink/Cherries.webp`,
    [normalize("🍓")]: `${BASE_URL}/Food%20and%20Drink/Strawberry.webp`,
    [normalize("🥝")]: `${BASE_URL}/Food%20and%20Drink/Kiwi%20Fruit.webp`,
    [normalize("🍅")]: `${BASE_URL}/Food%20and%20Drink/Tomato.webp`,
    [normalize("🥑")]: `${BASE_URL}/Food%20and%20Drink/Avocado.webp`,
    [normalize("🍆")]: `${BASE_URL}/Food%20and%20Drink/Eggplant.webp`,
    [normalize("🥕")]: `${BASE_URL}/Food%20and%20Drink/Carrot.webp`,
    [normalize("🌽")]: `${BASE_URL}/Food%20and%20Drink/Ear%20Of%20Corn.webp`,
    [normalize("🌶️")]: `${BASE_URL}/Food%20and%20Drink/Hot%20Pepper.webp`,
    [normalize("🥒")]: `${BASE_URL}/Food%20and%20Drink/Cucumber.webp`,
    [normalize("🥬")]: `${BASE_URL}/Food%20and%20Drink/Leafy%20Green.webp`,
    [normalize("🥦")]: `${BASE_URL}/Food%20and%20Drink/Broccoli.webp`,
    [normalize("🧄")]: `${BASE_URL}/Food%20and%20Drink/Garlic.webp`,
    [normalize("🧅")]: `${BASE_URL}/Food%20and%20Drink/Onion.webp`,
    [normalize("🍄")]: `${BASE_URL}/Food%20and%20Drink/Mushroom.webp`,
    [normalize("🌰")]: `${BASE_URL}/Food%20and%20Drink/Chestnut.webp`,
    [normalize("🍞")]: `${BASE_URL}/Food%20and%20Drink/Bread.webp`,
    [normalize("🥐")]: `${BASE_URL}/Food%20and%20Drink/Croissant.webp`,
    [normalize("🥯")]: `${BASE_URL}/Food%20and%20Drink/Bagel.webp`,
    [normalize("🧇")]: `${BASE_URL}/Food%20and%20Drink/Waffle.webp`,
    [normalize("🥞")]: `${BASE_URL}/Food%20and%20Drink/Pancakes.webp`,
    [normalize("🧀")]: `${BASE_URL}/Food%20and%20Drink/Cheese%20Wedge.webp`,
    [normalize("🍖")]: `${BASE_URL}/Food%20and%20Drink/Meat%20On%20Bone.webp`,
    [normalize("🍗")]: `${BASE_URL}/Food%20and%20Drink/Poultry%20Leg.webp`,
    [normalize("🥩")]: `${BASE_URL}/Food%20and%20Drink/Cut%20Of%20Meat.webp`,
    [normalize("🥓")]: `${BASE_URL}/Food%20and%20Drink/Bacon.webp`,
    [normalize("🍳")]: `${BASE_URL}/Food%20and%20Drink/Cooking.webp`,
    [normalize("🌭")]: `${BASE_URL}/Food%20and%20Drink/Hot%20Dog.webp`,
    [normalize("🍿")]: `${BASE_URL}/Food%20and%20Drink/Popcorn.webp`,
    [normalize("🧂")]: `${BASE_URL}/Food%20and%20Drink/Salt.webp`,
    [normalize("🥗")]: `${BASE_URL}/Food%20and%20Drink/Green%20Salad.webp`,
    [normalize("🍝")]: `${BASE_URL}/Food%20and%20Drink/Spaghetti.webp`,
    [normalize("🍜")]: `${BASE_URL}/Food%20and%20Drink/Steaming%20Bowl.webp`,
    [normalize("🍲")]: `${BASE_URL}/Food%20and%20Drink/Pot%20Of%20Food.webp`,
    [normalize("🍛")]: `${BASE_URL}/Food%20and%20Drink/Curry%20Rice.webp`,
    [normalize("🍣")]: `${BASE_URL}/Food%20and%20Drink/Sushi.webp`,
    [normalize("🍱")]: `${BASE_URL}/Food%20and%20Drink/Bento%20Box.webp`,
    [normalize("🥟")]: `${BASE_URL}/Food%20and%20Drink/Dumpling.webp`,
    [normalize("🍤")]: `${BASE_URL}/Food%20and%20Drink/Fried%20Shrimp.webp`,
    [normalize("🍙")]: `${BASE_URL}/Food%20and%20Drink/Rice%20Ball.webp`,
    [normalize("🍚")]: `${BASE_URL}/Food%20and%20Drink/Cooked%20Rice.webp`,
    [normalize("🍘")]: `${BASE_URL}/Food%20and%20Drink/Rice%20Cracker.webp`,
    [normalize("🍥")]: `${BASE_URL}/Food%20and%20Drink/Fish%20Cake%20With%20Swirl.webp`,
    [normalize("🥠")]: `${BASE_URL}/Food%20and%20Drink/Fortune%20Cookie.webp`,
    [normalize("🥮")]: `${BASE_URL}/Food%20and%20Drink/Moon%20Cake.webp`,
    [normalize("🍡")]: `${BASE_URL}/Food%20and%20Drink/Dango.webp`,
    [normalize("🍧")]: `${BASE_URL}/Food%20and%20Drink/Shaved%20Ice.webp`,
    [normalize("🍨")]: `${BASE_URL}/Food%20and%20Drink/Ice%20Cream.webp`,
    [normalize("🥧")]: `${BASE_URL}/Food%20and%20Drink/Pie.webp`,
    [normalize("🧁")]: `${BASE_URL}/Food%20and%20Drink/Cupcake.webp`,
    [normalize("🍪")]: `${BASE_URL}/Food%20and%20Drink/Cookie.webp`,
    [normalize("🍫")]: `${BASE_URL}/Food%20and%20Drink/Chocolate%20Bar.webp`,
    [normalize("🍬")]: `${BASE_URL}/Food%20and%20Drink/Candy.webp`,
    [normalize("🍭")]: `${BASE_URL}/Food%20and%20Drink/Lollipop.webp`,
    [normalize("🍮")]: `${BASE_URL}/Food%20and%20Drink/Custard.webp`,
    [normalize("🍯")]: `${BASE_URL}/Food%20and%20Drink/Honey%20Pot.webp`,
    [normalize("🍼")]: `${BASE_URL}/Food%20and%20Drink/Baby%20Bottle.webp`,
    [normalize("🥛")]: `${BASE_URL}/Food%20and%20Drink/Glass%20Of%20Milk.webp`,
    [normalize("🍵")]: `${BASE_URL}/Food%20and%20Drink/Teacup%20Without%20Handle.webp`,
    [normalize("🧃")]: `${BASE_URL}/Food%20and%20Drink/Beverage%20Box.webp`,
    [normalize("🧉")]: `${BASE_URL}/Food%20and%20Drink/Mate.webp`,
    [normalize("🧊")]: `${BASE_URL}/Food%20and%20Drink/Ice.webp`,
    [normalize("🍷")]: `${BASE_URL}/Food%20and%20Drink/Wine%20Glass.webp`,
    [normalize("🍸")]: `${BASE_URL}/Food%20and%20Drink/Cocktail%20Glass.webp`,
    [normalize("🍹")]: `${BASE_URL}/Food%20and%20Drink/Tropical%20Drink.webp`,
    [normalize("🍻")]: `${BASE_URL}/Food%20and%20Drink/Clinking%20Beer%20Mugs.webp`,
    [normalize("🥂")]: `${BASE_URL}/Food%20and%20Drink/Clinking%20Glasses.webp`,
    [normalize("🥃")]: `${BASE_URL}/Food%20and%20Drink/Tumbler%20Glass.webp`,
    
    // More Objects
    [normalize("⏰")]: `${BASE_URL}/Objects/Alarm%20Clock.webp`,
    [normalize("🕰️")]: `${BASE_URL}/Objects/Mantelpiece%20Clock.webp`,
    [normalize("⏳")]: `${BASE_URL}/Objects/Hourglass%20Not%20Done.webp`,
    [normalize("⌛")]: `${BASE_URL}/Objects/Hourglass%20Done.webp`,
    [normalize("📻")]: `${BASE_URL}/Objects/Radio.webp`,
    [normalize("📺")]: `${BASE_URL}/Objects/Television.webp`,
    [normalize("🎥")]: `${BASE_URL}/Objects/Movie%20Camera.webp`,
    [normalize("📽️")]: `${BASE_URL}/Objects/Film%20Projector.webp`,
    [normalize("🎬")]: `${BASE_URL}/Objects/Clapper%20Board.webp`,
    [normalize("📸")]: `${BASE_URL}/Objects/Camera%20With%20Flash.webp`,
    [normalize("🔦")]: `${BASE_URL}/Objects/Flashlight.webp`,
    [normalize("🔧")]: `${BASE_URL}/Objects/Wrench.webp`,
    [normalize("🔨")]: `${BASE_URL}/Objects/Hammer.webp`,
    [normalize("⚙️")]: `${BASE_URL}/Objects/Gear.webp`,
    [normalize("🔩")]: `${BASE_URL}/Objects/Nut%20And%20Bolt.webp`,
    [normalize("🔗")]: `${BASE_URL}/Objects/Link.webp`,
    [normalize("💊")]: `${BASE_URL}/Objects/Pill.webp`,
    [normalize("💉")]: `${BASE_URL}/Objects/Syringe.webp`,
    [normalize("🩺")]: `${BASE_URL}/Objects/Stethoscope.webp`,
    [normalize("🔬")]: `${BASE_URL}/Objects/Microscope.webp`,
    [normalize("🔭")]: `${BASE_URL}/Objects/Telescope.webp`,
    [normalize("📡")]: `${BASE_URL}/Objects/Satellite%20Antenna.webp`,
    [normalize("🛸")]: `${BASE_URL}/Travel%20and%20Places/Flying%20Saucer.webp`,
    [normalize("🚀")]: `${BASE_URL}/Travel%20and%20Places/Rocket.webp`,
    [normalize("✈️")]: `${BASE_URL}/Travel%20and%20Places/Airplane.webp`,
    [normalize("🚁")]: `${BASE_URL}/Travel%20and%20Places/Helicopter.webp`,
    [normalize("🚂")]: `${BASE_URL}/Travel%20and%20Places/Locomotive.webp`,
    [normalize("🚗")]: `${BASE_URL}/Travel%20and%20Places/Automobile.webp`,
    [normalize("🏎️")]: `${BASE_URL}/Travel%20and%20Places/Racing%20Car.webp`,
    [normalize("🏍️")]: `${BASE_URL}/Travel%20and%20Places/Motorcycle.webp`,
    [normalize("🚲")]: `${BASE_URL}/Travel%20and%20Places/Bicycle.webp`,
    [normalize("⛵")]: `${BASE_URL}/Travel%20and%20Places/Sailboat.webp`,
    [normalize("🚢")]: `${BASE_URL}/Travel%20and%20Places/Ship.webp`,
    [normalize("⚓")]: `${BASE_URL}/Travel%20and%20Places/Anchor.webp`,
    [normalize("🗽")]: `${BASE_URL}/Travel%20and%20Places/Statue%20Of%20Liberty.webp`,
    [normalize("🗼")]: `${BASE_URL}/Travel%20and%20Places/Tokyo%20Tower.webp`,
    [normalize("🏰")]: `${BASE_URL}/Travel%20and%20Places/Castle.webp`,
    [normalize("🏠")]: `${BASE_URL}/Travel%20and%20Places/House.webp`,
    [normalize("⛰️")]: `${BASE_URL}/Travel%20and%20Places/Mountain.webp`,
    [normalize("🌋")]: `${BASE_URL}/Travel%20and%20Places/Volcano.webp`,
    [normalize("🏝️")]: `${BASE_URL}/Travel%20and%20Places/Desert%20Island.webp`,
    [normalize("🌍")]: `${BASE_URL}/Travel%20and%20Places/Globe%20Showing%20Europe-Africa.webp`,
    [normalize("🌎")]: `${BASE_URL}/Travel%20and%20Places/Globe%20Showing%20Americas.webp`,
    [normalize("🌏")]: `${BASE_URL}/Travel%20and%20Places/Globe%20Showing%20Asia-Australia.webp`,
    [normalize("🌕")]: `${BASE_URL}/Travel%20and%20Places/Full%20Moon.webp`,
    [normalize("🌖")]: `${BASE_URL}/Travel%20and%20Places/Waning%20Gibbous%20Moon.webp`,
    [normalize("🌗")]: `${BASE_URL}/Travel%20and%20Places/Last%20Quarter%20Moon.webp`,
    [normalize("🌘")]: `${BASE_URL}/Travel%20and%20Places/Waning%20Crescent%20Moon.webp`,
    [normalize("🌑")]: `${BASE_URL}/Travel%20and%20Places/New%20Moon.webp`,
    [normalize("🌒")]: `${BASE_URL}/Travel%20and%20Places/Waxing%20Crescent%20Moon.webp`,
    [normalize("🌓")]: `${BASE_URL}/Travel%20and%20Places/First%20Quarter%20Moon.webp`,
    [normalize("🌔")]: `${BASE_URL}/Travel%20and%20Places/Waxing%20Gibbous%20Moon.webp`,
    [normalize("🌛")]: `${BASE_URL}/Travel%20and%20Places/First%20Quarter%20Moon%20Face.webp`,
    [normalize("🌜")]: `${BASE_URL}/Travel%20and%20Places/Last%20Quarter%20Moon%20Face.webp`,
    [normalize("🌝")]: `${BASE_URL}/Travel%20and%20Places/Full%20Moon%20Face.webp`,
    [normalize("🌞")]: `${BASE_URL}/Travel%20and%20Places/Sun%20With%20Face.webp`,
    [normalize("⭐")]: `${BASE_URL}/Travel%20and%20Places/Star.webp`,
    [normalize("🌟")]: `${BASE_URL}/Travel%20and%20Places/Glowing%20Star.webp`,
    [normalize("🌠")]: `${BASE_URL}/Travel%20and%20Places/Shooting%20Star.webp`,
    [normalize("☁️")]: `${BASE_URL}/Travel%20and%20Places/Cloud.webp`,
    [normalize("⛅")]: `${BASE_URL}/Travel%20and%20Places/Sun%20Behind%20Cloud.webp`,
    [normalize("🌧️")]: `${BASE_URL}/Travel%20and%20Places/Cloud%20With%20Rain.webp`,
    [normalize("⛈️")]: `${BASE_URL}/Travel%20and%20Places/Cloud%20With%20Lightning%20And%20Rain.webp`,
    [normalize("🌩️")]: `${BASE_URL}/Travel%20and%20Places/Cloud%20With%20Lightning.webp`,
    [normalize("🌨️")]: `${BASE_URL}/Travel%20and%20Places/Cloud%20With%20Snow.webp`,
    [normalize("☃️")]: `${BASE_URL}/Travel%20and%20Places/Snowman.webp`,
    [normalize("⛄")]: `${BASE_URL}/Travel%20and%20Places/Snowman%20Without%20Snow.webp`,
    [normalize("🌬️")]: `${BASE_URL}/Travel%20and%20Places/Wind%20Face.webp`,
    [normalize("🌀")]: `${BASE_URL}/Travel%20and%20Places/Cyclone.webp`,
    [normalize("🌪️")]: `${BASE_URL}/Travel%20and%20Places/Tornado.webp`,
    [normalize("🌫️")]: `${BASE_URL}/Travel%20and%20Places/Fog.webp`,
    [normalize("☔")]: `${BASE_URL}/Travel%20and%20Places/Umbrella%20With%20Rain%20Drops.webp`,
    
    // Flags
    [normalize("🏁")]: `${BASE_URL}/Flags/Chequered%20Flag.webp`,
    [normalize("🚩")]: `${BASE_URL}/Flags/Triangular%20Flag.webp`,
    [normalize("🏴")]: `${BASE_URL}/Flags/Black%20Flag.webp`,
    [normalize("🏳️")]: `${BASE_URL}/Flags/White%20Flag.webp`,
    [normalize("🏴‍☠️")]: `${BASE_URL}/Flags/Pirate%20Flag.webp`,
    [normalize("🇦🇷")]: `${BASE_URL}/Flags/Flag%20Argentina.webp`,
    [normalize("🇦🇲")]: `${BASE_URL}/Flags/Flag%20Armenia.webp`,
    [normalize("🇦🇹")]: `${BASE_URL}/Flags/Flag%20Austria.webp`,
    [normalize("🇧🇸")]: `${BASE_URL}/Flags/Flag%20Bahamas.webp`,
    [normalize("🇧🇾")]: `${BASE_URL}/Flags/Flag%20Belarus.webp`,
    [normalize("🇧🇪")]: `${BASE_URL}/Flags/Flag%20Belgium.webp`,
    [normalize("🇧🇯")]: `${BASE_URL}/Flags/Flag%20Benin.webp`,
    [normalize("🇧🇷")]: `${BASE_URL}/Flags/Flag%20Brazil.webp`,
    [normalize("🇧🇬")]: `${BASE_URL}/Flags/Flag%20Bulgaria.webp`,
    [normalize("🇧🇫")]: `${BASE_URL}/Flags/Flag%20Burkina%20Faso.webp`,
    [normalize("🇨🇲")]: `${BASE_URL}/Flags/Flag%20Cameroon.webp`,
    [normalize("🇹🇩")]: `${BASE_URL}/Flags/Flag%20Chad.webp`,
    [normalize("🇨🇳")]: `${BASE_URL}/Flags/Flag%20China.webp`,
    [normalize("🇨🇮")]: `${BASE_URL}/Flags/Flag%20Cote%20Divoire.webp`,
    [normalize("🇭🇷")]: `${BASE_URL}/Flags/Flag%20Croatia.webp`,
    [normalize("🇨🇿")]: `${BASE_URL}/Flags/Flag%20Czechia.webp`,
    [normalize("🇩🇯")]: `${BASE_URL}/Flags/Flag%20Djibouti.webp`,
    [normalize("🇬🇶")]: `${BASE_URL}/Flags/Flag%20Equatorial%20Guinea.webp`,
    [normalize("🇪🇪")]: `${BASE_URL}/Flags/Flag%20Estonia.webp`,
    [normalize("🇫🇷")]: `${BASE_URL}/Flags/Flag%20France.webp`,
    [normalize("🇬🇦")]: `${BASE_URL}/Flags/Flag%20Gabon.webp`,
    [normalize("🇩🇪")]: `${BASE_URL}/Flags/Flag%20Germany.webp`,
    [normalize("🇬🇭")]: `${BASE_URL}/Flags/Flag%20Ghana.webp`,
    [normalize("🇬🇼")]: `${BASE_URL}/Flags/Flag%20Guinea%20Bissau.webp`,
    [normalize("🇬🇳")]: `${BASE_URL}/Flags/Flag%20Guinea.webp`,
    [normalize("🇭🇺")]: `${BASE_URL}/Flags/Flag%20Hungary.webp`,
    [normalize("🇮🇳")]: `${BASE_URL}/Flags/Flag%20India.webp`,
    [normalize("🇮🇩")]: `${BASE_URL}/Flags/Flag%20Indonesia.webp`,
    [normalize("🇮🇪")]: `${BASE_URL}/Flags/Flag%20Ireland.webp`,
    [normalize("🇮🇹")]: `${BASE_URL}/Flags/Flag%20Italy.webp`,
    [normalize("🇯🇵")]: `${BASE_URL}/Flags/Flag%20Japan.webp`,
    [normalize("🇯🇴")]: `${BASE_URL}/Flags/Flag%20Jordan.webp`,
    [normalize("🇱🇹")]: `${BASE_URL}/Flags/Flag%20Lithuania.webp`,
    [normalize("🇱🇺")]: `${BASE_URL}/Flags/Flag%20Luxembourg.webp`,
    [normalize("🇲🇬")]: `${BASE_URL}/Flags/Flag%20Madagascar.webp`,
    [normalize("🇲🇱")]: `${BASE_URL}/Flags/Flag%20Mali.webp`,
    [normalize("🇲🇨")]: `${BASE_URL}/Flags/Flag%20Monaco.webp`,
    [normalize("🇲🇦")]: `${BASE_URL}/Flags/Flag%20Morocco.webp`,
    [normalize("🇲🇿")]: `${BASE_URL}/Flags/Flag%20Mozambique.webp`,
    [normalize("🇲🇲")]: `${BASE_URL}/Flags/Flag%20Myanmar%20Burma.webp`,
    [normalize("🇳🇱")]: `${BASE_URL}/Flags/Flag%20Netherlands.webp`,
    [normalize("🇳🇬")]: `${BASE_URL}/Flags/Flag%20Nigeria.webp`,
    [normalize("🇵🇸")]: `${BASE_URL}/Flags/Flag%20Palestinian%20Territories.webp`,
    [normalize("🇵🇪")]: `${BASE_URL}/Flags/Flag%20Peru.webp`,
    [normalize("🇵🇭")]: `${BASE_URL}/Flags/Flag%20Philippines.webp`,
    [normalize("🇵🇱")]: `${BASE_URL}/Flags/Flag%20Poland.webp`,
    [normalize("🇷🇴")]: `${BASE_URL}/Flags/Flag%20Romania.webp`,
    [normalize("🇷🇺")]: `${BASE_URL}/Flags/Flag%20Russia.webp`,
    [normalize("🇸🇹")]: `${BASE_URL}/Flags/Flag%20Sao%20Tome%20Principe.webp`,
    [normalize("🇸🇦")]: `${BASE_URL}/Flags/Flag%20Saudi%20Arabia.webp`,
    [normalize("🇸🇳")]: `${BASE_URL}/Flags/Flag%20Senegal.webp`,
    [normalize("🇸🇱")]: `${BASE_URL}/Flags/Flag%20Sierra%20Leone.webp`,
    [normalize("🇸🇬")]: `${BASE_URL}/Flags/Flag%20Singapore.webp`,
    [normalize("🇸🇽")]: `${BASE_URL}/Flags/Flag%20Sint%20Maarten.webp`,
    [normalize("🇸🇴")]: `${BASE_URL}/Flags/Flag%20Somalia.webp`,
    [normalize("🇰🇷")]: `${BASE_URL}/Flags/Flag%20South%20Korea.webp`,
    [normalize("🇸🇸")]: `${BASE_URL}/Flags/Flag%20South%20Sudan.webp`,
    [normalize("🇪🇸")]: `${BASE_URL}/Flags/Flag%20Spain.webp`,
    [normalize("🇸🇩")]: `${BASE_URL}/Flags/Flag%20Sudan.webp`,
    [normalize("🇺🇦")]: `${BASE_URL}/Flags/Flag%20Ukraine.webp`,
    [normalize("🇦🇪")]: `${BASE_URL}/Flags/Flag%20United%20Arab%20Emirates.webp`,
    [normalize("🇬🇧")]: `${BASE_URL}/Flags/Flag%20United%20Kingdom.webp`,
    [normalize("🇺🇸")]: `${BASE_URL}/Flags/Flag%20United%20States.webp`,
    [normalize("🇺🇿")]: `${BASE_URL}/Flags/Flag%20Uzbekistan.webp`,
    [normalize("🇻🇳")]: `${BASE_URL}/Flags/Flag%20Vietnam.webp`,
    [normalize("🇪🇭")]: `${BASE_URL}/Flags/Flag%20Western%20Sahara.webp`,
    [normalize("🇾🇪")]: `${BASE_URL}/Flags/Flag%20Yemen.webp`,
};

export const linkToBigEmoji = (content) => {
    if (!content) return null;
    const trimmed = normalize(content.trim());
    // Check if it's a known animated emoji
    if (ANIMATED_EMOJIS[trimmed]) {
        return ANIMATED_EMOJIS[trimmed];
    }
    return null;
}

// Helper to detect if content is only 1-3 emojis (for big display without bubble)
// Regex pattern covers most Unicode emoji ranges
const EMOJI_REGEX = /^(?:\p{Emoji_Presentation}|\p{Emoji}\uFE0F|\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|[\u{1F3F4}](?:\u{E0067}\u{E0062}(?:\u{E0065}\u{E006E}\u{E0067}|\u{E0073}\u{E0063}\u{E0074}|\u{E0077}\u{E006C}\u{E0073})\u{E007F})?|[\u{1F1E6}-\u{1F1FF}]{2})+$/u;

// Broader regex to catch all emoji-like characters including multi-char sequences
const EMOJI_TEST_REGEX = /^(?:\p{Extended_Pictographic}|\p{Emoji_Presentation}|\p{Emoji}\uFE0F|\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?)+$/u;

export const isSingleEmoji = (content) => {
    if (!content) return false;
    const trimmed = content.trim();
    if (!trimmed) return false;
    
    // Count grapheme clusters (visual characters) using Intl.Segmenter if available
    if (typeof Intl !== 'undefined' && Intl.Segmenter) {
        const segmenter = new Intl.Segmenter('en', { granularity: 'grapheme' });
        const Allsegments = [...segmenter.segment(trimmed)];
        
        // Filter out whitespace segments
        const segments = Allsegments.filter(seg => seg.segment.trim().length > 0);
        
        // Allow 1-3 emojis for big display
        if (segments.length < 1 || segments.length > 3) return false;

        // Verify each segment is likely an emoji
        return segments.every(seg => EMOJI_TEST_REGEX.test(seg.segment));
    }
    
    // Fallback: use strict regex and length check
    return EMOJI_REGEX.test(trimmed) && trimmed.length <= 14; 
}

// Split emoji content into individual emojis for separate rendering
export const splitEmojis = (content) => {
    if (!content) return [];
    const trimmed = content.trim();
    if (!trimmed) return [];
    
    if (typeof Intl !== 'undefined' && Intl.Segmenter) {
        const segmenter = new Intl.Segmenter('en', { granularity: 'grapheme' });
        return [...segmenter.segment(trimmed)]
            .map(s => s.segment)
            .filter(seg => seg.trim().length > 0);
    }
    
    // Fallback - basic split and filter spaces
    return [...trimmed].filter(c => c.trim().length > 0);
}
